// components/common/Card.tsx
import React from 'react';

interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
  className?: string;
}

export const Card: React.FC<CardProps> = ({ children, className = '', ...props }) => {
  return (
    <div {...props} className={`bg-brand-surface dark:bg-dark-surface rounded-xl shadow-sm p-6 dark:border dark:border-dark-border ${className}`}>
      {children}
    </div>
  );
};

// src/lib/components/common/Card.svelte
<script lang="ts">
    export let className: string = '';
    export let role: string | undefined = undefined;
    export let ariaLabel: string | undefined = undefined;
    export let ariaLabelledby: string | undefined = undefined;
    export let ariaDescribedby: string | undefined = undefined;
    export let tabindex: number | string | undefined = undefined;
</script>

<div 
    class={`bg-brand-surface dark:bg-dark-surface rounded-xl shadow-sm p-6 dark:border dark:border-dark-border ${className}`}
    {role}
    aria-label={ariaLabel}
    aria-labelledby={ariaLabelledby}
    aria-describedby={ariaDescribedby}
    {tabindex}
    {...$$restProps}
>
    <slot />
</div>
