// src/lib/components/Marketplace.svelte
<script lang="ts">
    import {
        MagnifyingGlassIcon,
        FunnelIcon,
    Squares2x2Icon,
        Bars3Icon,
        ChevronLeftIcon,
        ChevronRightIcon,
        InformationCircleIcon,
        WrenchScrewdriverIcon
    } from 'heroicons-svelte/24/outline';
    import Card from './common/Card.svelte';
    import Button from './common/Button.svelte';
    import ListingCard from './ListingCard.svelte';
    import ListingRow from './ListingRow.svelte';
    import ListingDetailModal from './ListingDetailModal.svelte';
    import type { Listing, ListingCategory, ToastMessage, AppView } from '$lib/types';
    import { createEventDispatcher } from 'svelte';

    export let showToast: (message: string, type?: ToastMessage['type']) => void;
    export let isAuthenticated: boolean = true;
    export let isCommunitySubscribed: boolean = false;
    export let listings: Listing[];
    export let onStartMessage: ((userId: string, userName: string) => void) | undefined = undefined;
    export let onLoginRequest: (() => void) | undefined = undefined;

    const dispatch = createEventDispatcher();

    let searchTerm = '';
    let sortBy = 'date-desc';
    let viewMode: 'grid' | 'list' = 'grid';
    let currentPage = 1;
    let itemsPerPage = 6;
    let activeCategory: ListingCategory | 'All' = 'All';
    let priceRange = { min: '', max: '' };
    let selectedListing: Listing | null = null;

    const categories: (ListingCategory | 'All')[] = ['All', 'Properties', 'Assets', 'Services'];

    $: processedListings = (() => {
        let filteredListings = listings.filter((l) => l.status === 'Active');

        if (activeCategory !== 'All') {
            filteredListings = filteredListings.filter((l) => l.category === activeCategory);
        }

        if (searchTerm.trim() !== '') {
            const lowercasedSearch = searchTerm.toLowerCase();
            filteredListings = filteredListings.filter(
                (l) =>
                    l.title.toLowerCase().includes(lowercasedSearch) ||
                    l.description.toLowerCase().includes(lowercasedSearch) ||
                    l.location.toLowerCase().includes(lowercasedSearch)
            );
        }

        const minPrice = parseFloat(priceRange.min);
        const maxPrice = parseFloat(priceRange.max);
        if (!isNaN(minPrice)) {
            filteredListings = filteredListings.filter((l) => l.price >= minPrice);
        }
        if (!isNaN(maxPrice)) {
            filteredListings = filteredListings.filter((l) => l.price <= maxPrice);
        }

        const sortedListings = [...filteredListings].sort((a, b) => {
            switch (sortBy) {
                case 'price-asc':
                    return a.price - b.price;
                case 'price-desc':
                    return b.price - a.price;
                case 'date-asc':
                    return new Date(a.dateListed).getTime() - new Date(b.dateListed).getTime();
                case 'date-desc':
                    return new Date(b.dateListed).getTime() - new Date(a.dateListed).getTime();
                case 'location-asc':
                    return a.location.localeCompare(b.location);
                case 'location-desc':
                    return b.location.localeCompare(a.location);
                case 'category-asc':
                    return a.category.localeCompare(b.category);
                case 'category-desc':
                    return b.category.localeCompare(a.category);
                default:
                    return 0;
            }
        });

        const paid = sortedListings.filter((l) => l.isPaid);
        const unpaid = sortedListings.filter((l) => !l.isPaid);

        return [...paid, ...unpaid];
    })();

    $: totalPages = Math.ceil(processedListings.length / itemsPerPage);
    $: currentListings = processedListings.slice(
        (currentPage - 1) * itemsPerPage,
        currentPage * itemsPerPage
    );

    $: {
        currentPage = 1;
        // We need to reference the dependencies of the reactive block
        // to make svelte re-run it when they change.
        activeCategory, searchTerm, sortBy, itemsPerPage, priceRange;
    }

    function onViewVendor(vendorName: string) {
        dispatch('viewvendor', vendorName);
    }

    function setActiveView(view: AppView) {
        dispatch('setactiveview', view);
    }
</script>

{#if selectedListing}
    <ListingDetailModal
        listing={selectedListing}
        on:close={() => (selectedListing = null)}
        {isAuthenticated}
        {onStartMessage}
        {onLoginRequest}
    />
{/if}

<div class="space-y-6">
    <Card>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div class="relative lg:col-span-2">
                <MagnifyingGlassIcon
                    class="h-5 w-5 text-gray-400 dark:text-gray-500 absolute top-1/2 left-3 transform -translate-y-1/2"
                />
                <input
                    type="text"
                    placeholder="Search listings by title, location..."
                    bind:value={searchTerm}
                    class="pl-10 pr-4 py-2 w-full bg-gray-100 dark:bg-gray-800 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary"
                />
            </div>
            <div class="flex items-center gap-2">
                <input
                    type="number"
                    placeholder="Min Price"
                    bind:value={priceRange.min}
                    class="pr-4 py-2 w-full bg-gray-100 dark:bg-gray-800 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary text-center"
                />
                <span class="text-gray-400">-</span>
                <input
                    type="number"
                    placeholder="Max Price"
                    bind:value={priceRange.max}
                    class="pr-4 py-2 w-full bg-gray-100 dark:bg-gray-800 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary text-center"
                />
            </div>
            <div class="flex items-center gap-4">
                <select
                    bind:value={sortBy}
                    class="p-2 w-full border border-brand-border dark:border-dark-border bg-brand-surface dark:bg-dark-surface rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary"
                >
                    <option value="date-desc">Newest First</option>
                    <option value="date-asc">Oldest First</option>
                    <option value="price-desc">Price: High to Low</option>
                    <option value="price-asc">Price: Low to High</option>
                    <option value="location-asc">Location (A-Z)</option>
                    <option value="location-desc">Location (Z-A)</option>
                    <option value="category-asc">Category (A-Z)</option>
                    <option value="category-desc">Category (Z-A)</option>
                </select>
                <div class="flex items-center bg-gray-100 dark:bg-gray-800 rounded-lg p-1">
                    <button
                        type="button"
                        on:click={() => (viewMode = 'grid')}
                        class={`p-1 rounded ${
                            viewMode === 'grid' ? 'bg-brand-surface dark:bg-dark-surface shadow' : ''
                        }`}
                        aria-label="Grid View"
                        aria-pressed={viewMode === 'grid'}
                    ><Squares2x2Icon class="h-5 w-5" /></button>
                    <button
                        type="button"
                        on:click={() => (viewMode = 'list')}
                        class={`p-1 rounded ${
                            viewMode === 'list' ? 'bg-brand-surface dark:bg-dark-surface shadow' : ''
                        }`}
                        aria-label="List View"
                        aria-pressed={viewMode === 'list'}
                    ><Bars3Icon class="h-5 w-5" /></button>
                </div>
            </div>
        </div>
        <div class="mt-4 border-b border-brand-border dark:border-dark-border">
            <nav class="-mb-px flex space-x-4 overflow-x-auto">
                {#each categories as category}
                    <button
                        type="button"
                        on:click={() => (activeCategory = category)}
                        aria-pressed={activeCategory === category}
                        class={`whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm ${
                            activeCategory === category
                                ? 'border-brand-primary text-brand-primary dark:border-dark-primary'
                                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                        }`}
                    >
                        {category}
                    </button>
                {/each}
            </nav>
        </div>
    </Card>

    {#if isAuthenticated}
        <div class="flex justify-end">
                <Button
                type="button"
                variant="secondary"
                on:click={() => setActiveView('MY_LISTINGS')}
                disabled={!isCommunitySubscribed}
                title={!isCommunitySubscribed ? 'Community subscription required to manage listings' : ''}
            >
                <WrenchScrewdriverIcon class="h-5 w-5 mr-2" />
                Manage My Listings
            </Button>
        </div>
    {/if}

    {#if currentListings.length > 0}
        {#if viewMode === 'grid'}
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {#each currentListings as listing (listing.id)}
                    <ListingCard
                        {listing}
                        on:open={(e) => (selectedListing = e.detail)}
                        on:viewvendor={(e) => onViewVendor(e.detail)}
                    />
                {/each}
            </div>
        {:else}
            <div class="space-y-4">
                {#each currentListings as listing (listing.id)}
                    <ListingRow
                        {listing}
                        on:open={(e) => (selectedListing = e.detail)}
                        on:viewvendor={(e) => onViewVendor(e.detail)}
                    />
                {/each}
            </div>
        {/if}
    {:else}
        <Card class="text-center py-16">
            <InformationCircleIcon class="h-12 w-12 text-gray-400 mx-auto mb-4" />
            <h3 class="text-xl font-bold">No listings found</h3>
            <p class="text-gray-500">Try adjusting your search or filters.</p>
        </Card>
    {/if}

    <Card class="flex flex-col md:flex-row justify-between items-center gap-4">
        <div class="flex items-center gap-2 text-sm">
            <span>Items per page:</span>
            <select
                bind:value={itemsPerPage}
                class="p-1 border border-brand-border dark:border-dark-border bg-brand-surface dark:bg-dark-surface rounded-md"
            >
                <option value={6}>6</option>
                <option value={12}>12</option>
                <option value={18}>18</option>
            </select>
        </div>
        <div class="flex items-center gap-2">
            <Button
                type="button"
                variant="secondary"
                on:click={() => (currentPage = Math.max(1, currentPage - 1))}
                disabled={currentPage === 1}
                aria-label="Previous page"
            >
                <ChevronLeftIcon class="h-5 w-5" />
            </Button>
            <span class="text-sm font-medium">Page {currentPage} of {totalPages}</span>
            <Button
                type="button"
                variant="secondary"
                on:click={() => (currentPage = Math.min(totalPages, currentPage + 1))}
                disabled={currentPage === totalPages}
                aria-label="Next page"
            >
                <ChevronRightIcon class="h-5 w-5" />
            </Button>
        </div>
    </Card>
</div>

// components/Marketplace.tsx
import React, { useState, useMemo } from 'react';
import { Card } from './common/Card';
import { Button } from './common/Button';
import { Listing, ListingCategory, ToastMessage, AppView } from '../types';
import { MagnifyingGlassIcon, FunnelIcon, Squares2X2Icon, Bars3Icon, ChevronLeftIcon, ChevronRightIcon, InformationCircleIcon, StarIcon, WrenchScrewdriverIcon } from '@heroicons/react/24/outline';
import { ListingDetailModal } from './ListingDetailModal';

const ListingCard: React.FC<{ listing: Listing; onViewVendor?: (vendorName: string) => void; onClick: () => void; }> = ({ listing, onViewVendor, onClick }) => (
    <Card className="group relative cursor-pointer" onClick={onClick}>
        {listing.isPaid && <div className="absolute top-2 right-2 bg-yellow-400 text-yellow-900 text-xs font-bold px-2 py-1 rounded-full flex items-center"><StarIcon className="h-4 w-4 mr-1"/>Paid</div>}
        <img src={listing.images[0]} alt={listing.title} className="w-full h-48 object-cover rounded-lg mb-4"/>
        <p className="text-sm text-gray-500 dark:text-dark-text-secondary">{listing.category}</p>
        <h3 className="text-lg font-bold truncate text-brand-text-primary dark:text-dark-text-primary group-hover:text-brand-primary dark:group-hover:text-dark-primary">{listing.title}</h3>
        <p className="font-semibold text-brand-primary dark:text-dark-primary text-xl">₦{listing.price.toLocaleString()}</p>
        <p className="text-sm text-gray-500 dark:text-dark-text-secondary truncate">{listing.location}</p>
        {onViewVendor && (
             <p className="text-xs text-gray-400 mt-1">by <button onClick={(e) => { e.stopPropagation(); onViewVendor(listing.vendorName); }} className="hover:underline font-semibold">{listing.vendorName}</button></p>
        )}
    </Card>
);

const ListingRow: React.FC<{ listing: Listing; onViewVendor?: (vendorName: string) => void; onClick: () => void; }> = ({ listing, onViewVendor, onClick }) => (
    <Card className="flex items-center space-x-4 mb-2 cursor-pointer" onClick={onClick}>
        <img src={listing.images[0]} alt={listing.title} className="w-24 h-24 object-cover rounded-lg flex-shrink-0"/>
        <div className="flex-1">
            <div className="flex items-center space-x-2">
                <p className="text-sm text-gray-500 dark:text-dark-text-secondary">{listing.category}</p>
                {listing.isPaid && <span className="text-xs bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300 font-bold px-2 py-0.5 rounded-full">Paid</span>}
            </div>
            <h3 className="text-lg font-bold text-brand-text-primary dark:text-dark-text-primary">{listing.title}</h3>
            <p className="text-sm text-gray-500 dark:text-dark-text-secondary">{listing.location}</p>
            {onViewVendor ? (
                 <p className="text-sm text-gray-500 dark:text-dark-text-secondary">by <button onClick={(e) => { e.stopPropagation(); onViewVendor(listing.vendorName); }} className="hover:underline font-semibold">{listing.vendorName}</button></p>
            ) : (
                 <p className="text-sm text-gray-500 dark:text-dark-text-secondary">by {listing.vendorName}</p>
            )}
        </div>
        <div className="text-right">
            <p className="font-semibold text-brand-primary dark:text-dark-primary text-xl">₦{listing.price.toLocaleString()}</p>
            <Button variant="secondary" className="mt-2 text-sm !py-1 !px-3">View Details</Button>
        </div>
    </Card>
);

interface MarketplaceProps {
    showToast: (message: string, type?: ToastMessage['type']) => void;
    isAuthenticated: boolean;
    setActiveView?: (view: AppView) => void;
    onViewVendor?: (vendorName: string) => void;
    isCommunitySubscribed: boolean;
    listings: Listing[];
    onStartMessage?: (userId: string, userName: string) => void;
    onLoginRequest?: () => void;
}

export const Marketplace: React.FC<MarketplaceProps> = ({ showToast, isAuthenticated = true, setActiveView, onViewVendor, isCommunitySubscribed = false, listings: allListings, onStartMessage, onLoginRequest }) => {
    const [searchTerm, setSearchTerm] = useState('');
    const [sortBy, setSortBy] = useState('date-desc');
    const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage, setItemsPerPage] = useState(6);
    const [activeCategory, setActiveCategory] = useState<ListingCategory | 'All'>('All');
    const [priceRange, setPriceRange] = useState({ min: '', max: '' });
    const [selectedListing, setSelectedListing] = useState<Listing | null>(null);
    
    const categories: (ListingCategory | 'All')[] = ['All', 'Properties', 'Assets', 'Services'];

    const processedListings = useMemo(() => {
        let listings = allListings.filter(l => l.status === 'Active');

        // 1. Filter by category
        if (activeCategory !== 'All') {
            listings = listings.filter(l => l.category === activeCategory);
        }

        // 2. Filter by search term
        if (searchTerm.trim() !== '') {
            const lowercasedSearch = searchTerm.toLowerCase();
            listings = listings.filter(l =>
                l.title.toLowerCase().includes(lowercasedSearch) ||
                l.description.toLowerCase().includes(lowercasedSearch) ||
                l.location.toLowerCase().includes(lowercasedSearch)
            );
        }
        
        // 3. Filter by price range
        const minPrice = parseFloat(priceRange.min);
        const maxPrice = parseFloat(priceRange.max);
        if (!isNaN(minPrice)) {
            listings = listings.filter(l => l.price >= minPrice);
        }
        if (!isNaN(maxPrice)) {
            listings = listings.filter(l => l.price <= maxPrice);
        }

        // 4. Sort
        const sortedListings = listings.sort((a, b) => {
            switch (sortBy) {
                case 'price-asc': return a.price - b.price;
                case 'price-desc': return b.price - a.price;
                case 'date-asc': return new Date(a.dateListed).getTime() - new Date(b.dateListed).getTime();
                case 'date-desc': return new Date(b.dateListed).getTime() - new Date(a.dateListed).getTime();
                case 'location-asc': return a.location.localeCompare(b.location);
                case 'location-desc': return b.location.localeCompare(a.location);
                case 'category-asc': return a.category.localeCompare(b.category);
                case 'category-desc': return b.category.localeCompare(a.category);
                default: return 0;
            }
        });
        
        // 5. Prioritize paid listings
        const paid = sortedListings.filter(l => l.isPaid);
        const unpaid = sortedListings.filter(l => !l.isPaid);

        return [...paid, ...unpaid];
    }, [allListings, activeCategory, searchTerm, sortBy, priceRange]);

    const totalPages = Math.ceil(processedListings.length / itemsPerPage);
    const currentListings = useMemo(() => {
        const start = (currentPage - 1) * itemsPerPage;
        const end = start + itemsPerPage;
        return processedListings.slice(start, end);
    }, [processedListings, currentPage, itemsPerPage]);

    React.useEffect(() => {
        setCurrentPage(1);
    }, [activeCategory, searchTerm, sortBy, itemsPerPage, priceRange]);

    return (
        <>
        {selectedListing && (
            <ListingDetailModal
                listing={selectedListing}
                onClose={() => setSelectedListing(null)}
                isAuthenticated={isAuthenticated}
                onStartMessage={onStartMessage}
                onLoginRequest={onLoginRequest}
            />
        )}
        <div className="space-y-6">
            <Card>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                    <div className="relative lg:col-span-2">
                        <MagnifyingGlassIcon className="h-5 w-5 text-gray-400 dark:text-gray-500 absolute top-1/2 left-3 transform -translate-y-1/2" />
                        <input 
                            type="text" 
                            placeholder="Search listings by title, location..." 
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="pl-10 pr-4 py-2 w-full bg-gray-100 dark:bg-gray-800 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary"
                        />
                    </div>
                    <div className="flex items-center gap-2">
                         <input 
                            type="number"
                            placeholder="Min Price"
                            value={priceRange.min}
                            onChange={e => setPriceRange({...priceRange, min: e.target.value})}
                            className="pr-4 py-2 w-full bg-gray-100 dark:bg-gray-800 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary text-center"
                        />
                        <span className="text-gray-400">-</span>
                        <input 
                            type="number"
                            placeholder="Max Price"
                            value={priceRange.max}
                            onChange={e => setPriceRange({...priceRange, max: e.target.value})}
                            className="pr-4 py-2 w-full bg-gray-100 dark:bg-gray-800 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary text-center"
                        />
                    </div>
                    <div className="flex items-center gap-4">
                        <select
                            value={sortBy}
                            onChange={(e) => setSortBy(e.target.value)}
                            className="p-2 w-full border border-brand-border dark:border-dark-border bg-brand-surface dark:bg-dark-surface rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-primary"
                        >
                            <option value="date-desc">Newest First</option>
                            <option value="date-asc">Oldest First</option>
                            <option value="price-desc">Price: High to Low</option>
                            <option value="price-asc">Price: Low to High</option>
                            <option value="location-asc">Location (A-Z)</option>
                            <option value="location-desc">Location (Z-A)</option>
                            <option value="category-asc">Category (A-Z)</option>
                            <option value="category-desc">Category (Z-A)</option>
                        </select>
                        <div className="flex items-center bg-gray-100 dark:bg-gray-800 rounded-lg p-1">
                            <button onClick={() => setViewMode('grid')} className={`p-1 rounded ${viewMode === 'grid' ? 'bg-brand-surface dark:bg-dark-surface shadow' : ''}`} aria-label="Grid View"><Squares2X2Icon className="h-5 w-5" /></button>
                            <button onClick={() => setViewMode('list')} className={`p-1 rounded ${viewMode === 'list' ? 'bg-brand-surface dark:bg-dark-surface shadow' : ''}`} aria-label="List View"><Bars3Icon className="h-5 w-5" /></button>
                        </div>
                    </div>
                </div>
                <div className="mt-4 border-b border-brand-border dark:border-dark-border">
                    <nav className="-mb-px flex space-x-4 overflow-x-auto">
                        {categories.map(category => (
                            <button 
                                key={category}
                                onClick={() => setActiveCategory(category)}
                                className={`whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm ${activeCategory === category ? 'border-brand-primary text-brand-primary dark:border-dark-primary' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'}`}
                            >
                                {category}
                            </button>
                        ))}
                    </nav>
                </div>
            </Card>

            {isAuthenticated && (
                <div className="flex justify-end">
                    <Button variant="secondary" onClick={() => setActiveView && setActiveView(AppView.MY_LISTINGS)} disabled={!isCommunitySubscribed} title={!isCommunitySubscribed ? 'Community subscription required to manage listings' : ''}>
                       <WrenchScrewdriverIcon className="h-5 w-5 mr-2" />
                        Manage My Listings
                    </Button>
                </div>
            )}

            {currentListings.length > 0 ? (
                viewMode === 'grid' ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {currentListings.map(listing => <ListingCard key={listing.id} listing={listing} onViewVendor={onViewVendor} onClick={() => setSelectedListing(listing)} />)}
                    </div>
                ) : (
                    <div className="space-y-4">
                        {currentListings.map(listing => <ListingRow key={listing.id} listing={listing} onViewVendor={onViewVendor} onClick={() => setSelectedListing(listing)} />)}
                    </div>
                )
            ) : (
                <Card className="text-center py-16">
                    <InformationCircleIcon className="h-12 w-12 text-gray-400 mx-auto mb-4"/>
                    <h3 className="text-xl font-bold">No listings found</h3>
                    <p className="text-gray-500">Try adjusting your search or filters.</p>
                </Card>
            )}
            
            <Card className="flex flex-col md:flex-row justify-between items-center gap-4">
                <div className="flex items-center gap-2 text-sm">
                    <span>Items per page:</span>
                    <select
                        value={itemsPerPage}
                        onChange={(e) => setItemsPerPage(Number(e.target.value))}
                        className="p-1 border border-brand-border dark:border-dark-border bg-brand-surface dark:bg-dark-surface rounded-md"
                    >
                        <option value={6}>6</option>
                        <option value={12}>12</option>
                        <option value={18}>18</option>
                    </select>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="secondary" onClick={() => setCurrentPage(p => Math.max(1, p - 1))} disabled={currentPage === 1}><ChevronLeftIcon className="h-5 w-5" /></Button>
                    <span className="text-sm font-medium">Page {currentPage} of {totalPages}</span>
                    <Button variant="secondary" onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))} disabled={currentPage === totalPages}><ChevronRightIcon className="h-5 w-5" /></Button>
                </div>
            </Card>

        </div>
        </>
    );
};
