// src/lib/components/PublicHomePage.svelte
<script lang="ts">
  import Marketplace from './Marketplace.svelte';
  import LoginModal from './LoginModal.svelte';
  import Button from './common/Button.svelte';
  import { createEventDispatcher } from 'svelte';

  export let onLoginSuccess: ()=>void = ()=>{};
  export let listings: any[] = [];

  let isLoginModalOpen = false;
  const dispatch = createEventDispatcher();

  function openLogin() { isLoginModalOpen = true; }
  function closeLogin() { isLoginModalOpen = false; }
</script>

<div class="min-h-screen bg-brand-background text-brand-text-primary">
  <header class="bg-brand-surface p-4 border-b border-brand-border">
    <div class="container mx-auto flex items-center justify-between">
      <div class="flex items-center">
        <svg aria-hidden="true" focusable="false" class="h-10 w-10 text-brand-primary" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z"/></svg>
        <h1 class="text-2xl font-bold text-brand-primary ml-2">Creeb</h1>
      </div>
      <div class="flex items-center space-x-2">
  <Button type="button" variant="secondary" on:click={openLogin} aria-label="Open login dialog" title="Login">Login</Button>
  <Button type="button" variant="primary" aria-label="Sign up for Creeb" title="Sign up">Sign Up</Button>
      </div>
    </div>
  </header>

  <main class="p-6 lg:p-8">
    <Marketplace showToast={(m)=>console.log(m)} isAuthenticated={false} listings={listings} on:loginRequest={() => (isLoginModalOpen = true)} isCommunitySubscribed={false} />
  </main>

  {#if isLoginModalOpen}
    <LoginModal on:login={() => { isLoginModalOpen = false; onLoginSuccess(); }} on:close={() => (isLoginModalOpen = false)} />
  {/if}
</div>

// components/PublicHomePage.tsx
import React, { useState } from 'react';
import { Marketplace } from './Marketplace';
import { LoginModal } from './LoginModal';
import { Button } from './common/Button';
import { ToastMessage, Listing } from '../types';

interface PublicHomePageProps {
    onLoginSuccess: () => void;
    listings: Listing[];
}

const PublicHeader: React.FC<{ onLoginClick: () => void }> = ({ onLoginClick }) => (
    <header className="bg-brand-surface dark:bg-dark-surface p-4 border-b border-brand-border dark:border-dark-border">
        <div className="container mx-auto flex items-center justify-between">
            <div className="flex items-center">
                <svg className="h-10 w-10 text-brand-primary dark:text-dark-primary" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z" />
                </svg>
                <h1 className="text-2xl font-bold text-brand-primary dark:text-dark-text-primary ml-2">Creeb</h1>
            </div>
            <div className="flex items-center space-x-2">
                <Button variant="secondary" onClick={onLoginClick}>Login</Button>
                <Button variant="primary">Sign Up</Button>
            </div>
        </div>
    </header>
);

export const PublicHomePage: React.FC<PublicHomePageProps> = ({ onLoginSuccess, listings }) => {
    const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
    
    const showToast = (message: string, type: ToastMessage['type'] = 'success') => {
      console.log(`Toast: [${type}] ${message}`);
    };

    return (
        <div className="min-h-screen bg-brand-background dark:bg-dark-background text-brand-text-primary dark:text-dark-text-primary">
            <PublicHeader onLoginClick={() => setIsLoginModalOpen(true)} />
            <main className="p-6 lg:p-8">
                <Marketplace 
                    showToast={showToast} 
                    isAuthenticated={false} 
                    listings={listings} 
                    onLoginRequest={() => setIsLoginModalOpen(true)}
                    isCommunitySubscribed={false}
                />
            </main>
            {isLoginModalOpen && (
                <LoginModal 
                    onLogin={() => {
                        setIsLoginModalOpen(false);
                        onLoginSuccess();
                    }} 
                    onClose={() => setIsLoginModalOpen(false)} 
                />
            )}
        </div>
    );
};
